export const FullFormData = [
  {
    type: 'Computer',
    typeIcon: '<i class="fa-solid fa-computer"></i>',
    DataFF: [
      { sortF: 'CPU', fullF: 'Central Processing Unit' },
      { sortF: 'GPU', fullF: 'Graphics Processing Unit' },
      { sortF: 'RAM', fullF: 'Random Access Memory' },
      { sortF: 'ROM', fullF: 'Read Only Memory' },
      { sortF: 'SSD', fullF: 'Solid State Drive' },
      { sortF: 'HDD', fullF: 'Hard Disk Drive' },
      { sortF: 'BIOS', fullF: 'Basic Input Output System' },
      { sortF: 'OS', fullF: 'Operating System' },
      { sortF: 'USB', fullF: 'Universal Serial Bus' },
      { sortF: 'LAN', fullF: 'Local Area Network' },
      { sortF: 'PAN', fullF: 'Parsonal Area Network' },
      { sortF: 'WAN', fullF: 'Wide Area Network' },
      { sortF: 'VPN', fullF: 'Virtual Private Network' },
      { sortF: 'IP', fullF: 'Internet Protocol' },
      { sortF: 'MAC', fullF: 'Media Access Control' },
      { sortF: 'DNS', fullF: 'Domain Name System' },
      { sortF: 'DHCP', fullF: 'Dynamic Host Configuration Protocol' },
      { sortF: 'HTTP', fullF: 'HyperText Transfer Protocol' },
      { sortF: 'HTTPS', fullF: 'HyperText Transfer Protocol Secure' },
      { sortF: 'FTP', fullF: 'File Transfer Protocol' },
      { sortF: 'SMTP', fullF: 'Simple Mail Transfer Protocol' },
      { sortF: 'TCP', fullF: 'Transmission Control Protocol' },
      { sortF: 'UDP', fullF: 'User Datagram Protocol' },
      { sortF: 'ICMP', fullF: 'Internet Control Message Protocol' },
      { sortF: 'ARP', fullF: 'Address Resolution Protocol' },
      { sortF: 'NAT', fullF: 'Network Address Translation' },
      { sortF: 'URL', fullF: 'Uniform Resource Locator' },
      { sortF: 'URI', fullF: 'Uniform Resource Identifier' },
      { sortF: 'HTML', fullF: 'HyperText Markup Language' },
      { sortF: 'XML', fullF: 'eXtensible Markup Language' },
      { sortF: 'SQL', fullF: 'Structured Query Language' },
    ]
  },
  {
    type: 'Programming',
    typeIcon: '<i class="fa-solid fa-code"></i>',
    DataFF: [
      { sortF: 'HTML', fullF: 'HyperText Markup Language' },
      { sortF: 'CSS', fullF: 'Cascading Style Sheets' },
      { sortF: 'JS', fullF: 'JavaScript' },
      { sortF: 'JSON', fullF: 'JavaScript Object Notation' },
      { sortF: 'API', fullF: 'Application Programming Interface' },
      { sortF: 'OOP', fullF: 'Object Oriented Programming' },
      { sortF: 'DBMS', fullF: 'Database Management System' },
      { sortF: 'SQL', fullF: 'Structured Query Language' },
      { sortF: 'PHP', fullF: 'Hypertext Preprocessor' },
      { sortF: 'IDE', fullF: 'Integrated Development Environment' },
      { sortF: 'SDK', fullF: 'Software Development Kit' },
      { sortF: 'MVC', fullF: 'Model View Controller' },
      { sortF: 'CI/CD', fullF: 'Continuous Integration / Continuous Deployment' },
      { sortF: 'DOM', fullF: 'Document Object Model' },
      { sortF: 'AJAX', fullF: 'Asynchronous JavaScript and XML' },
      { sortF: 'JSONP', fullF: 'JSON with Padding' },
      { sortF: 'PWA', fullF: 'Progressive Web App' },
      { sortF: 'SPA', fullF: 'Single Page Application' },
      { sortF: 'SSR', fullF: 'Server Side Rendering' },
      { sortF: 'CSR', fullF: 'Client Side Rendering' },
      { sortF: 'REST', fullF: 'Representational State Transfer' },
      { sortF: 'SOAP', fullF: 'Simple Object Access Protocol' },
      { sortF: 'GraphQL', fullF: 'Graph Query Language' },
      { sortF: 'YAML', fullF: 'YAML Ain Markup Language' },
      { sortF: 'XML', fullF: 'eXtensible Markup Language' },
      { sortF: 'XSS', fullF: 'Cross Site Scripting' },
      { sortF: 'CSRF', fullF: 'Cross Site Request Forgery' },
      { sortF: 'SQLi', fullF: 'SQL Injection' },
      { sortF: 'CLI', fullF: 'Command Line Interface' },
      { sortF: 'GUI', fullF: 'Graphical User Interface' }
    ]
  },
  {
    type: 'AI & Data',
    typeIcon: '<i class="fa-solid fa-robot"></i>',
    DataFF: [
      { sortF: 'AI', fullF: 'Artificial Intelligence' },
      { sortF: 'ML', fullF: 'Machine Learning' },
      { sortF: 'DL', fullF: 'Deep Learning' },
      { sortF: 'NLP', fullF: 'Natural Language Processing' },
      { sortF: 'CNN', fullF: 'Convolutional Neural Network' },
      { sortF: 'RNN', fullF: 'Recurrent Neural Network' },
      { sortF: 'ANN', fullF: 'Artificial Neural Network' },
      { sortF: 'IoT', fullF: 'Internet of Things' },
      { sortF: 'Big Data', fullF: 'Large-Scale Data Analysis' },
      { sortF: 'API', fullF: 'Application Programming Interface' },
      { sortF: 'GAN', fullF: 'Generative Adversarial Network' },
      { sortF: 'RNN', fullF: 'Recurrent Neural Network' },
      { sortF: 'LSTM', fullF: 'Long Short-Term Memory' },
      { sortF: 'SVM', fullF: 'Support Vector Machine' },
      { sortF: 'KNN', fullF: 'K-Nearest Neighbors' },
      { sortF: 'PCA', fullF: 'Principal Component Analysis' },
      { sortF: 'EDA', fullF: 'Exploratory Data Analysis' },
      { sortF: 'ETL', fullF: 'Extract Transform Load' },
      { sortF: 'ELT', fullF: 'Extract Load Transform' },
      { sortF: 'OLAP', fullF: 'Online Analytical Processing' },
      { sortF: 'OLTP', fullF: 'Online Transaction Processing' },
      { sortF: 'NoSQL', fullF: 'Not Only SQL' },
      { sortF: 'RDBMS', fullF: 'Relational Database Management System' },
      { sortF: 'ACID', fullF: 'Atomicity Consistency Isolation Durability' },
      { sortF: 'CAP', fullF: 'Consistency Availability Partition Tolerance' }
    ]
  },
  {
    type: 'Software',
    typeIcon: '<i class="fa-solid fa-mobile-screen-button"></i>',
    DataFF: [
      { sortF: 'OS', fullF: 'Operating System' },
      { sortF: 'SaaS', fullF: 'Software as a Service' },
      { sortF: 'PaaS', fullF: 'Platform as a Service' },
      { sortF: 'IaaS', fullF: 'Infrastructure as a Service' },
      { sortF: 'FaaS', fullF: 'Function as a Service' },
      { sortF: 'CRM', fullF: 'Customer Relationship Management' },
      { sortF: 'ERP', fullF: 'Enterprise Resource Planning' },
      { sortF: 'CMS', fullF: 'Content Management System' },
      { sortF: 'LMS', fullF: 'Learning Management System' },
      { sortF: 'SCM', fullF: 'Supply Chain Management' },
      { sortF: 'BI', fullF: 'Business Intelligence' },
      { sortF: 'DMS', fullF: 'Document Management System' },
      { sortF: 'HRM', fullF: 'Human Resource Management' },
      { sortF: 'POS', fullF: 'Point of Sale' },
      { sortF: 'KMS', fullF: 'Knowledge Management System' },
      { sortF: 'TMS', fullF: 'Transportation Management System' },
      { sortF: 'WMS', fullF: 'Warehouse Management System' },
      { sortF: 'BPM', fullF: 'Business Process Management' },
      { sortF: 'RPA', fullF: 'Robotic Process Automation' },
      { sortF: 'BPA', fullF: 'Business Process Automation' }
    ]
  },
  {
    type: 'Hardware',
    typeIcon: '<i class="fa-solid fa-microchip"></i>',
    DataFF: [
      { sortF: 'CPU', fullF: 'Central Processing Unit' },
      { sortF: 'GPU', fullF: 'Graphics Processing Unit' },
      { sortF: 'APU', fullF: 'Accelerated Processing Unit' },
      { sortF: 'TPU', fullF: 'Tensor Processing Unit' },
      { sortF: 'FPU', fullF: 'Floating Point Unit' },
      { sortF: 'ALU', fullF: 'Arithmetic Logic Unit' },
      { sortF: 'CU', fullF: 'Control Unit' },
      { sortF: 'RAM', fullF: 'Random Access Memory' },
      { sortF: 'ROM', fullF: 'Read Only Memory' },
      { sortF: 'PROM', fullF: 'Programmable Read Only Memory' },
      { sortF: 'EPROM', fullF: 'Erasable Programmable Read Only Memory' },
      { sortF: 'EEPROM', fullF: 'Electrically Erasable Programmable Read Only Memory' },
      { sortF: 'HDD', fullF: 'Hard Disk Drive' },
      { sortF: 'SSD', fullF: 'Solid State Drive' },
      { sortF: 'NVMe', fullF: 'Non-Volatile Memory Express' },
      { sortF: 'SATA', fullF: 'Serial Advanced Technology Attachment' },
      { sortF: 'PATA', fullF: 'Parallel Advanced Technology Attachment' },
      { sortF: 'SCSI', fullF: 'Small Computer System Interface' },
      { sortF: 'RAID', fullF: 'Redundant Array of Independent Disks' },
      { sortF: 'NIC', fullF: 'Network Interface Card' }
    ]
  },
  {
    type: 'school',
    typeIcon: '<i class="fa-solid fa-meteor"></i>',
    DataFF: [
      { sortF: 'PTA', fullF: 'Parent Teacher Association' },
      { sortF: 'SSC', fullF: 'Secondary School Certificate' },
      { sortF: 'HSC', fullF: 'Higher Secondary Certificate' },
      { sortF: 'GPA', fullF: 'Grade Point Average' },
      { sortF: 'CGPA', fullF: 'Cumulative Grade Point Average' },
      { sortF: 'SAT', fullF: 'Scholastic Assessment Test' },
      { sortF: 'ACT', fullF: 'American College Testing' },
      { sortF: 'TOEFL', fullF: 'Test of English as a Foreign Language' },
      { sortF: 'IELTS', fullF: 'International English Language Testing System' },
      { sortF: 'GRE', fullF: 'Graduate Record Examination' },
      { sortF: 'GMAT', fullF: 'Graduate Management Admission Test' },
      { sortF: 'MCQ', fullF: 'Multiple Choice Question' },
      { sortF: 'VIVA', fullF: 'Oral Examination' },
      { sortF: 'STEM', fullF: 'Science Technology Engineering Mathematics' },
      { sortF: 'ICT', fullF: 'Information and Communication Technology' },
      { sortF: 'RO', fullF: 'Register Office' },
      { sortF: 'HO', fullF: 'Head Office' },
      { sortF: 'CR', fullF: 'Class Representative' },
      { sortF: 'AR', fullF: 'Attendance Register' },
      { sortF: 'ID', fullF: 'Identification Document' }
    ]
  },
  {
    type: 'Business',
    typeIcon: '<i class="fa-solid fa-business-time"></i>',
    DataFF: [
      { sortF: 'CEO', fullF: 'Chief Executive Officer' },
      { sortF: 'CFO', fullF: 'Chief Financial Officer' },
      { sortF: 'COO', fullF: 'Chief Operating Officer' },
      { sortF: 'CTO', fullF: 'Chief Technology Officer' },
      { sortF: 'CMO', fullF: 'Chief Marketing Officer' },
      { sortF: 'HR', fullF: 'Human Resources' },
      { sortF: 'PR', fullF: 'Public Relations' },
      { sortF: 'R&D', fullF: 'Research and Development' },
      { sortF: 'QA', fullF: 'Quality Assurance' },
      { sortF: 'QC', fullF: 'Quality Control' },
      { sortF: 'KPI', fullF: 'Key Performance Indicator' },
      { sortF: 'ROI', fullF: 'Return on Investment' },
      { sortF: 'B2B', fullF: 'Business to Business' },
      { sortF: 'B2C', fullF: 'Business to Consumer' },
      { sortF: 'C2C', fullF: 'Consumer to Consumer' },
      { sortF: 'B2G', fullF: 'Business to Government' },
      { sortF: 'IPO', fullF: 'Initial Public Offering' },
      { sortF: 'SME', fullF: 'Small and Medium Enterprises' },
      { sortF: 'MNC', fullF: 'Multinational Corporation' },
      { sortF: 'LLC', fullF: 'Limited Liability Company' }
    ]
  },
  {
    type: 'Electrical',
    typeIcon: '<i class="fa-solid fa-bolt"></i>',
    DataFF: [
      { sortF: 'AC', fullF: 'Alternating Current' },
      { sortF: 'DC', fullF: 'Direct Current' },
      { sortF: 'V', fullF: 'Voltage' },
      { sortF: 'A', fullF: 'Ampere' },
      { sortF: 'W', fullF: 'Watt' },
      { sortF: 'kWh', fullF: 'Kilowatt Hour' },
      { sortF: 'Hz', fullF: 'Hertz' },
      { sortF: 'Ω', fullF: 'Ohm' },
      { sortF: 'F', fullF: 'Farad' },
      { sortF: 'H', fullF: 'Henry' },
      { sortF: 'LED', fullF: 'Light Emitting Diode' },
      { sortF: 'LCD', fullF: 'Liquid Crystal Display' },
      { sortF: 'PCB', fullF: 'Printed Circuit Board' },
      { sortF: 'IC', fullF: 'Integrated Circuit' },
      { sortF: 'VLSI', fullF: 'Very Large Scale Integration' },
      { sortF: 'ULSI', fullF: 'Ultra Large Scale Integration' },
      { sortF: 'MOSFET', fullF: 'Metal Oxide Semiconductor Field Effect Transistor' },
      { sortF: 'BJT', fullF: 'Bipolar Junction Transistor' },
      { sortF: 'FET', fullF: 'Field Effect Transistor' },
      { sortF: 'IGBT', fullF: 'Insulated Gate Bipolar Transistor' }
    ]
  },
  {
    type: 'Educational',
    typeIcon: '<i class="fa-solid fa-graduation-cap"></i>',
    DataFF: [
      { sortF: 'UNESCO', fullF: 'United Nations Educational Scientific and Cultural Organization' },
      { sortF: 'UGC', fullF: 'University Grants Commission' },
      { sortF: 'NCTB', fullF: 'National Curriculum and Textbook Board' },
      { sortF: 'NAAC', fullF: 'National Assessment and Accreditation Council' },
      { sortF: 'AICTE', fullF: 'All India Council for Technical Education' },
      { sortF: 'NCERT', fullF: 'National Council of Educational Research and Training' },
      { sortF: 'CBSE', fullF: 'Central Board of Secondary Education' },
      { sortF: 'ICSE', fullF: 'Indian Certificate of Secondary Education' },
      { sortF: 'IGCSE', fullF: 'International General Certificate of Secondary Education' },
      { sortF: 'IB', fullF: 'International Baccalaureate' },
      { sortF: 'MOOC', fullF: 'Massive Open Online Course' },
      { sortF: 'LMS', fullF: 'Learning Management System' },
      { sortF: 'CMS', fullF: 'Content Management System' },
      { sortF: 'VLE', fullF: 'Virtual Learning Environment' },
      { sortF: 'PBL', fullF: 'Project Based Learning' },
      { sortF: 'CBL', fullF: 'Competency Based Learning' },
      { sortF: 'F2F', fullF: 'Face to Face' },
      { sortF: 'ODL', fullF: 'Open and Distance Learning' },
      { sortF: 'HEI', fullF: 'Higher Education Institution' },
      { sortF: 'VET', fullF: 'Vocational Education and Training' }
    ]
  },
  {
    type: 'Medical',
    typeIcon: '<i class="fa-brands fa-accessible-icon"></i>',
    DataFF: [
      { sortF: 'DNA', fullF: 'Deoxyribonucleic Acid' },
      { sortF: 'RNA', fullF: 'Ribonucleic Acid' },
      { sortF: 'COVID', fullF: 'Coronavirus Disease' },
      { sortF: 'HIV', fullF: 'Human Immunodeficiency Virus' },
      { sortF: 'AIDS', fullF: 'Acquired Immunodeficiency Syndrome' },
      { sortF: 'BMI', fullF: 'Body Mass Index' },
      { sortF: 'BP', fullF: 'Blood Pressure' },
      { sortF: 'ECG', fullF: 'Electrocardiogram' },
      { sortF: 'EEG', fullF: 'Electroencephalogram' },
      { sortF: 'MRI', fullF: 'Magnetic Resonance Imaging' },
      { sortF: 'CT', fullF: 'Computed Tomography' },
      { sortF: 'X-ray', fullF: 'X-radiation' },
      { sortF: 'ICU', fullF: 'Intensive Care Unit' },
      { sortF: 'OPD', fullF: 'Outpatient Department' },
      { sortF: 'IPD', fullF: 'Inpatient Department' },
      { sortF: 'WHO', fullF: 'World Health Organization' },
      { sortF: 'CDC', fullF: 'Centers for Disease Control and Prevention' },
      { sortF: 'FDA', fullF: 'Food and Drug Administration' },
      { sortF: 'NHS', fullF: 'National Health Service' },
      { sortF: 'EMR', fullF: 'Electronic Medical Record' }
    ]
  },
  {
    type: 'Government',
    typeIcon: '<i class="fa-solid fa-fire"></i>',
    DataFF: [
      { sortF: 'UN', fullF: 'United Nations' },
      { sortF: 'UNICEF', fullF: "United Nations International Children's Emergency Fund" },
      { sortF: 'WHO', fullF: 'World Health Organization' },
      { sortF: 'WTO', fullF: 'World Trade Organization' },
      { sortF: 'IMF', fullF: 'International Monetary Fund' },
      { sortF: 'UNESCO', fullF: 'United Nations Educational Scientific and Cultural Organization' },
      { sortF: 'NASA', fullF: 'National Aeronautics and Space Administration' },
      { sortF: 'FBI', fullF: 'Federal Bureau of Investigation' },
      { sortF: 'CIA', fullF: 'Central Intelligence Agency' },
      { sortF: 'IRS', fullF: 'Internal Revenue Service' },
      { sortF: 'VAT', fullF: 'Value Added Tax' },
      { sortF: 'GST', fullF: 'Goods and Services Tax' },
      { sortF: 'TIN', fullF: 'Taxpayer Identification Number' },
      { sortF: 'PAN', fullF: 'Permanent Account Number' },
      { sortF: 'AADHAR', fullF: 'Unique Identification Authority of India' },
      { sortF: 'NRC', fullF: 'National Register of Citizens' },
      { sortF: 'RTI', fullF: 'Right to Information' },
      { sortF: 'RTE', fullF: 'Right to Education' },
      { sortF: 'MLA', fullF: 'Member of Legislative Assembly' },
      { sortF: 'MP', fullF: 'Member of Parliament' }
    ]
  },
  {
    type: 'Military',
    typeIcon: '<i class="fa-solid fa-jet-fighter"></i>',
    DataFF: [
      { sortF: 'UN', fullF: 'United Nations' },
      { sortF: 'NATO', fullF: 'North Atlantic Treaty Organization' },
      { sortF: 'UNSC', fullF: 'United Nations Security Council' },
      { sortF: 'IAF', fullF: 'Indian Air Force' },
      { sortF: 'INA', fullF: 'Indian National Army' },
      { sortF: 'RAW', fullF: 'Research and Analysis Wing' },
      { sortF: 'IB', fullF: 'Intelligence Bureau' },
      { sortF: 'CBI', fullF: 'Central Bureau of Investigation' },
      { sortF: 'NSG', fullF: 'National Security Guard' },
      { sortF: 'BSF', fullF: 'Border Security Force' },
      { sortF: 'CRPF', fullF: 'Central Reserve Police Force' },
      { sortF: 'CISF', fullF: 'Central Industrial Security Force' },
      { sortF: 'SSB', fullF: 'Sashastra Seema Bal' },
      { sortF: 'ITBP', fullF: 'Indo-Tibetan Border Police' },
      { sortF: 'NSG', fullF: 'National Security Guard' },
      { sortF: 'MARCOS', fullF: 'Marine Commandos' },
      { sortF: 'GARUD', fullF: 'Indian Air Force Special Forces' },
      { sortF: 'PARA', fullF: 'Parachute Regiment' },
      { sortF: 'COAS', fullF: 'Chief of Army Staff' },
      { sortF: 'CAS', fullF: 'Chief of Air Staff' }
    ]
  }
]